version: 0.2

phases:
  pre_build:
    commands:
       - terraform --version
       - terraform init
       - terraform validate
  build:
    commands:
       - terraform apply --auto-approve
  post_build:
    commands:
       - echo terraform apply completed on `date`