version: 0.2

phases:
  install:
    commands:
       - yum install wget -y
       - yum install unzip -y
  pre_build:
    commands:
       - wget https://releases.hashicorp.com/terraform/1.3.5/terraform_1.3.5_linux_amd64.zip
       - unzip terraform_1.3.5_linux_amd64.zip
       - mv terraform /usr/local/bin/
       - terraform --version
  build:
    commands:
       - terraform init
       - terraform validate
       - terraform apply --auto-approve
  post_build:
    commands:
       - echo terraform apply completed on `date`