version: 0.2

phases:
  install:
    commands:
       - yum install -y yum-utils
       - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
       - yum -y install terraform
  pre_build:
    commands:
       - mv terraform /usr/local/bin/
       - terraform --version
       - terraform init
       - terraform validate
  build:
    commands:
       - terraform plan
  post_build:
    commands:
       - echo terraform plan completed on `date`