version: 0.2

phases:
  install:
    commands:
       - yum install -y wget unzip
       - wget https://releases.hashicorp.com/terraform/1.3.5/terraform_1.3.5_linux_amd64.zip
       - unzip terraform_1.3.5_linux_amd64.zip -d /usr/local/bin/
  pre_build:
    commands:
       - terraform --version
       - terraform init
       - terraform validate
  build:
    commands:
       - terraform apply --auto-approve
  post_build:
    commands:
       - echo terraform apply completed on `date`